# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-03 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0006_auto_20200203_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='today-pics/'),
        ),
    ]
